################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Generated_Code/AD1.c \
../Generated_Code/AS1.c \
../Generated_Code/ASerialLdd1.c \
../Generated_Code/AdcLdd1.c \
../Generated_Code/BitIoLdd1.c \
../Generated_Code/BitIoLdd12.c \
../Generated_Code/BitIoLdd13.c \
../Generated_Code/BitIoLdd2.c \
../Generated_Code/BitIoLdd8.c \
../Generated_Code/BitIoLdd9.c \
../Generated_Code/CDC1.c \
../Generated_Code/CE1.c \
../Generated_Code/CLS1.c \
../Generated_Code/CS1.c \
../Generated_Code/CSN1.c \
../Generated_Code/Cpu.c \
../Generated_Code/ExtIntLdd1.c \
../Generated_Code/ExtIntLdd2.c \
../Generated_Code/ExtIntLdd3.c \
../Generated_Code/ExtIntLdd4.c \
../Generated_Code/ExtIntLdd5.c \
../Generated_Code/FRTOS1.c \
../Generated_Code/GI2C1.c \
../Generated_Code/HF1.c \
../Generated_Code/I2C1.c \
../Generated_Code/IFsh1.c \
../Generated_Code/IntFlashLdd1.c \
../Generated_Code/LedBit1.c \
../Generated_Code/LedBit2.c \
../Generated_Code/MMA1.c \
../Generated_Code/PE_LDD.c \
../Generated_Code/PTA.c \
../Generated_Code/RApp.c \
../Generated_Code/RF1.c \
../Generated_Code/RMAC.c \
../Generated_Code/RMSG.c \
../Generated_Code/RNET1.c \
../Generated_Code/RNWK.c \
../Generated_Code/RPHY.c \
../Generated_Code/RStack.c \
../Generated_Code/RStdIO.c \
../Generated_Code/RTOSCNTRLDD1.c \
../Generated_Code/Radio.c \
../Generated_Code/Rx1.c \
../Generated_Code/SM1.c \
../Generated_Code/SMasterLdd1.c \
../Generated_Code/SW1.c \
../Generated_Code/SW2.c \
../Generated_Code/SW3.c \
../Generated_Code/SW4.c \
../Generated_Code/SW5.c \
../Generated_Code/SW6.c \
../Generated_Code/SW7.c \
../Generated_Code/TMOUT1.c \
../Generated_Code/Tx1.c \
../Generated_Code/USB0.c \
../Generated_Code/USB1.c \
../Generated_Code/UTIL1.c \
../Generated_Code/Vectors.c \
../Generated_Code/WAIT1.c \
../Generated_Code/croutine.c \
../Generated_Code/event_groups.c \
../Generated_Code/heap_1.c \
../Generated_Code/heap_2.c \
../Generated_Code/heap_3.c \
../Generated_Code/heap_4.c \
../Generated_Code/list.c \
../Generated_Code/port.c \
../Generated_Code/queue.c \
../Generated_Code/tasks.c \
../Generated_Code/timers.c \
../Generated_Code/usb_cdc.c \
../Generated_Code/usb_cdc_pstn.c \
../Generated_Code/usb_class.c \
../Generated_Code/usb_dci_kinetis.c \
../Generated_Code/usb_descriptor.c \
../Generated_Code/usb_driver.c \
../Generated_Code/usb_framework.c \
../Generated_Code/wdt_kinetis.c 

OBJS += \
./Generated_Code/AD1.o \
./Generated_Code/AS1.o \
./Generated_Code/ASerialLdd1.o \
./Generated_Code/AdcLdd1.o \
./Generated_Code/BitIoLdd1.o \
./Generated_Code/BitIoLdd12.o \
./Generated_Code/BitIoLdd13.o \
./Generated_Code/BitIoLdd2.o \
./Generated_Code/BitIoLdd8.o \
./Generated_Code/BitIoLdd9.o \
./Generated_Code/CDC1.o \
./Generated_Code/CE1.o \
./Generated_Code/CLS1.o \
./Generated_Code/CS1.o \
./Generated_Code/CSN1.o \
./Generated_Code/Cpu.o \
./Generated_Code/ExtIntLdd1.o \
./Generated_Code/ExtIntLdd2.o \
./Generated_Code/ExtIntLdd3.o \
./Generated_Code/ExtIntLdd4.o \
./Generated_Code/ExtIntLdd5.o \
./Generated_Code/FRTOS1.o \
./Generated_Code/GI2C1.o \
./Generated_Code/HF1.o \
./Generated_Code/I2C1.o \
./Generated_Code/IFsh1.o \
./Generated_Code/IntFlashLdd1.o \
./Generated_Code/LedBit1.o \
./Generated_Code/LedBit2.o \
./Generated_Code/MMA1.o \
./Generated_Code/PE_LDD.o \
./Generated_Code/PTA.o \
./Generated_Code/RApp.o \
./Generated_Code/RF1.o \
./Generated_Code/RMAC.o \
./Generated_Code/RMSG.o \
./Generated_Code/RNET1.o \
./Generated_Code/RNWK.o \
./Generated_Code/RPHY.o \
./Generated_Code/RStack.o \
./Generated_Code/RStdIO.o \
./Generated_Code/RTOSCNTRLDD1.o \
./Generated_Code/Radio.o \
./Generated_Code/Rx1.o \
./Generated_Code/SM1.o \
./Generated_Code/SMasterLdd1.o \
./Generated_Code/SW1.o \
./Generated_Code/SW2.o \
./Generated_Code/SW3.o \
./Generated_Code/SW4.o \
./Generated_Code/SW5.o \
./Generated_Code/SW6.o \
./Generated_Code/SW7.o \
./Generated_Code/TMOUT1.o \
./Generated_Code/Tx1.o \
./Generated_Code/USB0.o \
./Generated_Code/USB1.o \
./Generated_Code/UTIL1.o \
./Generated_Code/Vectors.o \
./Generated_Code/WAIT1.o \
./Generated_Code/croutine.o \
./Generated_Code/event_groups.o \
./Generated_Code/heap_1.o \
./Generated_Code/heap_2.o \
./Generated_Code/heap_3.o \
./Generated_Code/heap_4.o \
./Generated_Code/list.o \
./Generated_Code/port.o \
./Generated_Code/queue.o \
./Generated_Code/tasks.o \
./Generated_Code/timers.o \
./Generated_Code/usb_cdc.o \
./Generated_Code/usb_cdc_pstn.o \
./Generated_Code/usb_class.o \
./Generated_Code/usb_dci_kinetis.o \
./Generated_Code/usb_descriptor.o \
./Generated_Code/usb_driver.o \
./Generated_Code/usb_framework.o \
./Generated_Code/wdt_kinetis.o 

C_DEPS += \
./Generated_Code/AD1.d \
./Generated_Code/AS1.d \
./Generated_Code/ASerialLdd1.d \
./Generated_Code/AdcLdd1.d \
./Generated_Code/BitIoLdd1.d \
./Generated_Code/BitIoLdd12.d \
./Generated_Code/BitIoLdd13.d \
./Generated_Code/BitIoLdd2.d \
./Generated_Code/BitIoLdd8.d \
./Generated_Code/BitIoLdd9.d \
./Generated_Code/CDC1.d \
./Generated_Code/CE1.d \
./Generated_Code/CLS1.d \
./Generated_Code/CS1.d \
./Generated_Code/CSN1.d \
./Generated_Code/Cpu.d \
./Generated_Code/ExtIntLdd1.d \
./Generated_Code/ExtIntLdd2.d \
./Generated_Code/ExtIntLdd3.d \
./Generated_Code/ExtIntLdd4.d \
./Generated_Code/ExtIntLdd5.d \
./Generated_Code/FRTOS1.d \
./Generated_Code/GI2C1.d \
./Generated_Code/HF1.d \
./Generated_Code/I2C1.d \
./Generated_Code/IFsh1.d \
./Generated_Code/IntFlashLdd1.d \
./Generated_Code/LedBit1.d \
./Generated_Code/LedBit2.d \
./Generated_Code/MMA1.d \
./Generated_Code/PE_LDD.d \
./Generated_Code/PTA.d \
./Generated_Code/RApp.d \
./Generated_Code/RF1.d \
./Generated_Code/RMAC.d \
./Generated_Code/RMSG.d \
./Generated_Code/RNET1.d \
./Generated_Code/RNWK.d \
./Generated_Code/RPHY.d \
./Generated_Code/RStack.d \
./Generated_Code/RStdIO.d \
./Generated_Code/RTOSCNTRLDD1.d \
./Generated_Code/Radio.d \
./Generated_Code/Rx1.d \
./Generated_Code/SM1.d \
./Generated_Code/SMasterLdd1.d \
./Generated_Code/SW1.d \
./Generated_Code/SW2.d \
./Generated_Code/SW3.d \
./Generated_Code/SW4.d \
./Generated_Code/SW5.d \
./Generated_Code/SW6.d \
./Generated_Code/SW7.d \
./Generated_Code/TMOUT1.d \
./Generated_Code/Tx1.d \
./Generated_Code/USB0.d \
./Generated_Code/USB1.d \
./Generated_Code/UTIL1.d \
./Generated_Code/Vectors.d \
./Generated_Code/WAIT1.d \
./Generated_Code/croutine.d \
./Generated_Code/event_groups.d \
./Generated_Code/heap_1.d \
./Generated_Code/heap_2.d \
./Generated_Code/heap_3.d \
./Generated_Code/heap_4.d \
./Generated_Code/list.d \
./Generated_Code/port.d \
./Generated_Code/queue.d \
./Generated_Code/tasks.d \
./Generated_Code/timers.d \
./Generated_Code/usb_cdc.d \
./Generated_Code/usb_cdc_pstn.d \
./Generated_Code/usb_class.d \
./Generated_Code/usb_dci_kinetis.d \
./Generated_Code/usb_descriptor.d \
./Generated_Code/usb_driver.d \
./Generated_Code/usb_framework.d \
./Generated_Code/wdt_kinetis.d 


# Each subdirectory must supply rules for building sources it contributes
Generated_Code/%.o: ../Generated_Code/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections  -g3 -DPL_BOARD_IS_FRDM -I"C:\Freescale\KDS_1.1.1\eclipse\ProcessorExpert/lib/Kinetis/pdd/inc" -I"C:\Freescale\KDS_1.1.1\eclipse\ProcessorExpert/lib/Kinetis/iofiles" -I"C:/Users/tbsimmen/Documents/INTRO_RobotFiles/FRDM_/Sources" -I"C:/Users/tbsimmen/Documents/INTRO_RobotFiles/FRDM_/Generated_Code" -I"C:\Users\tbsimmen\Documents\INTRO_RobotFiles\Common" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


