/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : MMA1.c
**     CDE edition : Standard
**     Project     : FRDM_
**     Processor   : MKL25Z128VLK4
**     Component   : MMA8451Q
**     Version     : Component 01.028, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-12-10, 09:08, # CodeGen: 1
**     Abstract    :
**         Implements a Driver for the MMA8451 accelerometer from Freescale.
**     Settings    :
**          Component Name                                 : MMA1
**          Slave Address                                  : 1D
**          I2C Bus                                        : GI2C1
**          Constant Offsets                               : Enabled
**            X offset                                     : 0
**            Y offset                                     : 0
**            Z offset                                     : 0
**          Shell                                          : Enabled
**            Shell                                        : CLS1
**            Utility                                      : UTIL1
**     Contents    :
**         Enable         - byte MMA1_Enable(void);
**         Disable        - byte MMA1_Disable(void);
**         isEnabled      - byte MMA1_isEnabled(bool *isEnabled);
**         GetX           - int16_t MMA1_GetX(void);
**         GetY           - int16_t MMA1_GetY(void);
**         GetZ           - int16_t MMA1_GetZ(void);
**         GetRaw8XYZ     - uint8_t MMA1_GetRaw8XYZ(void* *xyz);
**         GetXmg         - int16_t MMA1_GetXmg(void);
**         GetYmg         - int16_t MMA1_GetYmg(void);
**         GetZmg         - int16_t MMA1_GetZmg(void);
**         MeasureGetRawX - word MMA1_MeasureGetRawX(void);
**         MeasureGetRawY - word MMA1_MeasureGetRawY(void);
**         MeasureGetRawZ - word MMA1_MeasureGetRawZ(void);
**         GetXOffset     - int16_t MMA1_GetXOffset(void);
**         GetYOffset     - int16_t MMA1_GetYOffset(void);
**         GetZOffset     - int16_t MMA1_GetZOffset(void);
**         GetX1gValue    - int16_t MMA1_GetX1gValue(void);
**         GetY1gValue    - int16_t MMA1_GetY1gValue(void);
**         GetZ1gValue    - int16_t MMA1_GetZ1gValue(void);
**         SetFastMode    - byte MMA1_SetFastMode(bool on);
**         Init           - uint8_t MMA1_Init(void);
**         Deinit         - uint8_t MMA1_Deinit(void);
**         ParseCommand   - byte MMA1_ParseCommand(const unsigned char *cmd, bool *handled, const...
**
**     License : Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2013, all rights reserved.
**     http://www.mcuoneclipse.com
**     This an open source software in the form of a Processor Expert Embedded Component.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file MMA1.c
** @version 01.00
** @brief
**         Implements a Driver for the MMA8451 accelerometer from Freescale.
*/         
/*!
**  @addtogroup MMA1_module MMA1 module documentation
**  @{
*/         

/* MODULE MMA1. */

#include "MMA1.h"

#define MMA1_CPU_IS_LITTLE_ENDIAN 1 /* Cpu is little endian */

/* External 3-axis accelerometer control register addresses */
#define MMA1_CTRL_REG_1 0x2A
/* MMA8451 3-axis accelerometer control register bit masks */
#define MMA1_ACTIVE_BIT_MASK 0x01
#define MMA1_F_READ_BIT_MASK 0x02

/* External 3-axis accelerometer data register addresses */
#define MMA1_OUT_X_MSB 0x01
#define MMA1_OUT_X_LSB 0x02
#define MMA1_OUT_Y_MSB 0x03
#define MMA1_OUT_Y_LSB 0x04
#define MMA1_OUT_Z_MSB 0x05
#define MMA1_OUT_Z_LSB 0x06

#define MMA1_I2C_ADDR   (0x1D) /* I2C slave device address as set in the properties */

/* constant offsets specified in properties */
#define CalNxOff 0
#define CalNyOff 0
#define CalNzOff 0

static uint8_t PrintStatus(const CLS1_StdIOType *io) {
  unsigned char buf[8];
  uint16_t val;
  bool isEnabled;
  uint8_t res;

  CLS1_SendStatusStr((unsigned char*)"MMA1", (unsigned char*)"\r\n", io->stdOut);

  res = MMA1_isEnabled(&isEnabled);
  if (res!=ERR_OK) {
    UTIL1_strcpy(buf, sizeof(buf), (unsigned char*)"FAIL!\r\n");
  } else {
    if (isEnabled) {
      UTIL1_strcpy(buf, sizeof(buf), (unsigned char*)"yes\r\n");
    } else {
      UTIL1_strcpy(buf, sizeof(buf), (unsigned char*)"no\r\n");
    }
  }
  CLS1_SendStatusStr((unsigned char*)"  enabled", buf, io->stdOut);
  if (res!=ERR_OK) { /* do not access the device if not enabled */
    return ERR_OK;
  }

  CLS1_SendStatusStr((unsigned char*)"  raw", (unsigned char*)"0x", io->stdOut);
  val = MMA1_MeasureGetRawX();
  buf[0] = '\0';
  UTIL1_strcatNum16Hex(buf, sizeof(buf), (uint16_t)val);
  CLS1_SendStr(buf, io->stdOut);
  CLS1_SendStr((unsigned char*)" (", io->stdOut);
  CLS1_SendNum16s((int16_t)val, io->stdOut);
  CLS1_SendStr((unsigned char*)"), 0x", io->stdOut);

  val = MMA1_MeasureGetRawY();
  buf[0] = '\0';
  UTIL1_strcatNum16Hex(buf, sizeof(buf), (uint16_t)val);
  CLS1_SendStr(buf, io->stdOut);
  CLS1_SendStr((unsigned char*)" (", io->stdOut);
  CLS1_SendNum16s((int16_t)val, io->stdOut);
  CLS1_SendStr((unsigned char*)"), 0x", io->stdOut);

  val = MMA1_MeasureGetRawZ();
  buf[0] = '\0';
  UTIL1_strcatNum16Hex(buf, sizeof(buf), (uint16_t)val);
  CLS1_SendStr(buf, io->stdOut);
  CLS1_SendStr((unsigned char*)" (", io->stdOut);
  CLS1_SendNum16s((int16_t)val, io->stdOut);
  CLS1_SendStr((unsigned char*)")\r\n", io->stdOut);

  CLS1_SendStatusStr((unsigned char*)"  calibOffset", (unsigned char*)"", io->stdOut);
  CLS1_SendNum16s(MMA1_GetXOffset(), io->stdOut);
  CLS1_SendStr((unsigned char*)" ", io->stdOut);
  CLS1_SendNum16s(MMA1_GetYOffset(), io->stdOut);
  CLS1_SendStr((unsigned char*)" ", io->stdOut);
  CLS1_SendNum16s(MMA1_GetZOffset(), io->stdOut);
  CLS1_SendStr((unsigned char*)"\r\n", io->stdOut);

  CLS1_SendStatusStr((unsigned char*)"  calib 1g", (unsigned char*)"", io->stdOut);
  CLS1_SendNum16s(MMA1_GetX1gValue(), io->stdOut);
  CLS1_SendStr((unsigned char*)" ", io->stdOut);
  CLS1_SendNum16s(MMA1_GetY1gValue(), io->stdOut);
  CLS1_SendStr((unsigned char*)" ", io->stdOut);
  CLS1_SendNum16s(MMA1_GetZ1gValue(), io->stdOut);
  CLS1_SendStr((unsigned char*)"\r\n", io->stdOut);

  CLS1_SendStatusStr((unsigned char*)"  GetX,Y,Z", (unsigned char*)"", io->stdOut);
  CLS1_SendNum16s(MMA1_GetX(), io->stdOut);
  CLS1_SendStr((unsigned char*)" ", io->stdOut);
  CLS1_SendNum16s(MMA1_GetY(), io->stdOut);
  CLS1_SendStr((unsigned char*)" ", io->stdOut);
  CLS1_SendNum16s(MMA1_GetZ(), io->stdOut);
  CLS1_SendStr((unsigned char*)" (raw+offset)\r\n", io->stdOut);

  CLS1_SendStatusStr((unsigned char*)"  mg X,Y,Z", (unsigned char*)"", io->stdOut);
  CLS1_SendNum16s(MMA1_GetXmg(), io->stdOut);
  CLS1_SendStr((unsigned char*)" ", io->stdOut);
  CLS1_SendNum16s(MMA1_GetYmg(), io->stdOut);
  CLS1_SendStr((unsigned char*)" ", io->stdOut);
  CLS1_SendNum16s(MMA1_GetZmg(), io->stdOut);
  CLS1_SendStr((unsigned char*)" (milli-g)\r\n", io->stdOut);
  return ERR_OK;
}

static uint8_t PrintHelp(const CLS1_StdIOType *io) {
  CLS1_SendHelpStr((unsigned char*)"MMA1", (unsigned char*)"Group of MMA1 commands\r\n", io->stdOut);
  CLS1_SendHelpStr((unsigned char*)"  help|status", (unsigned char*)"Print help or status information\r\n", io->stdOut);
  CLS1_SendHelpStr((unsigned char*)"  enable|disable", (unsigned char*)"Enables or disables the sensor\r\n", io->stdOut);
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  MMA1_GetRaw8XYZ (component MMA8451Q)
**     Description :
**         Returns in an array the x, y and z accelerometer as 8bit
**         values.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * xyz             - Pointer to an array of three unsigned 8bit
**                           values which are used to return the
**                           accelerometer values.
**     Returns     :
**         ---             - Error code, ERR_OK for no error.
** ===================================================================
*/
uint8_t MMA1_GetRaw8XYZ(uint8_t *xyz)
{
  static const uint8_t addr = MMA1_OUT_X_MSB;

  return GI2C1_ReadAddress(MMA1_I2C_ADDR, (uint8_t*)&addr, sizeof(addr), &xyz[0], 3);
}

/*
** ===================================================================
**     Method      :  MMA1_Deinit (component MMA8451Q)
**     Description :
**         Counterpart to Init() method.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, ERR_OK if everything is ok.
** ===================================================================
*/
uint8_t MMA1_Deinit(void)
{
  return ERR_OK; /* nothing to do */
}

/*
** ===================================================================
**     Method      :  MMA1_Init (component MMA8451Q)
**     Description :
**         Initializes the device driver
**     Parameters  : None
**     Returns     :
**         ---             - Error code, ERR_OK if everything is ok.
** ===================================================================
*/
uint8_t MMA1_Init(void)
{
  return GI2C1_WriteByteAddress8(MMA1_I2C_ADDR, MMA1_CTRL_REG_1, MMA1_ACTIVE_BIT_MASK); /* enable device */
}

/*
** ===================================================================
**     Method      :  MMA1_GetXmg (component MMA8451Q)
**     Description :
**         Returns the X value in mg
**     Parameters  : None
**     Returns     :
**         ---             - The g value in 1/1000g units
** ===================================================================
*/
int16_t MMA1_GetXmg(void)
{
  int16_t val;

  val = MMA1_GetX();
  /* with 14bits and 2g mode, each count corresponds to 0.25 mg */
  return (int16_t)((val>>2)/4); /* remove 2 bits (16bit to 14bit) and scale */
}

/*
** ===================================================================
**     Method      :  MMA1_GetYmg (component MMA8451Q)
**     Description :
**         Returns the Y value in mg
**     Parameters  : None
**     Returns     :
**         ---             - The g value in 1/1000g units
** ===================================================================
*/
int16_t MMA1_GetYmg(void)
{
  int16_t val;

  val = MMA1_GetY();
  /* with 14bits and 2g mode, each count corresponds to 0.25 mg */
  return (int16_t)((val>>2)/4); /* remove 2 bits (16bit to 14bit) and scale */
}

/*
** ===================================================================
**     Method      :  MMA1_GetZmg (component MMA8451Q)
**     Description :
**         Returns the Z value in mg
**     Parameters  : None
**     Returns     :
**         ---             - The g value in 1/1000g units
** ===================================================================
*/
int16_t MMA1_GetZmg(void)
{
  int16_t val;

  val = MMA1_GetZ();
  /* with 14bits and 2g mode, each count corresponds to 0.25 mg */
  return (int16_t)((val>>2)/4); /* remove 2 bits (16bit to 14bit) and scale */
}

/*
** ===================================================================
**     Method      :  MMA1_MeasureGetRawX (component MMA8451Q)
**     Description :
**         Performs a measurement on X channel and returns the raw
**         value.
**     Parameters  : None
**     Returns     :
**         ---             - X sensor value
** ===================================================================
*/
word MMA1_MeasureGetRawX(void)
{
  union {
    uint8_t buf[2]; /* value from device is in big endian */
    uint16_t be;
  } val;
  static const uint8_t addr = MMA1_OUT_X_MSB;

  if(GI2C1_ReadAddress(MMA1_I2C_ADDR, (uint8_t*)&addr, sizeof(addr), &val.buf[0], sizeof(val.buf))!=ERR_OK) {
    return 0; /* failure */
  }
#if MMA1_CPU_IS_LITTLE_ENDIAN
  return (uint16_t)((val.buf[0]<<8)|val.buf[1]); /* transform into LE value */
#else
  return val.be; /* already in BE */
#endif
}

/*
** ===================================================================
**     Method      :  MMA1_MeasureGetRawY (component MMA8451Q)
**     Description :
**         Performs a measurement on Y channel and returns the raw
**         value.
**     Parameters  : None
**     Returns     :
**         ---             - Y sensor value
** ===================================================================
*/
word MMA1_MeasureGetRawY(void)
{
  union {
    uint8_t buf[2]; /* value from device is in big endian */
    uint16_t be;
  } val;
  static const uint8_t addr = MMA1_OUT_Y_MSB;

  if(GI2C1_ReadAddress(MMA1_I2C_ADDR, (uint8_t*)&addr, sizeof(addr), &val.buf[0], sizeof(val.buf))!=ERR_OK) {
    return 0; /* failure */
  }
#if MMA1_CPU_IS_LITTLE_ENDIAN
  return (uint16_t)((val.buf[0]<<8)|val.buf[1]); /* transform into LE value */
#else
  return val.be; /* already in BE */
#endif
}

/*
** ===================================================================
**     Method      :  MMA1_MeasureGetRawZ (component MMA8451Q)
**     Description :
**         Performs a measurement on Z channel and returns the raw
**         value.
**     Parameters  : None
**     Returns     :
**         ---             - Z sensor value
** ===================================================================
*/
word MMA1_MeasureGetRawZ(void)
{
  union {
    uint8_t buf[2]; /* value from device is in big endian */
    uint16_t be;
  } val;
  static const uint8_t addr = MMA1_OUT_Z_MSB;

  if(GI2C1_ReadAddress(MMA1_I2C_ADDR, (uint8_t*)&addr, sizeof(addr), &val.buf[0], sizeof(val.buf))!=ERR_OK) {
    return 0; /* failure */
  }
#if MMA1_CPU_IS_LITTLE_ENDIAN
  return (uint16_t)((val.buf[0]<<8)|val.buf[1]); /* transform into LE value */
#else
  return val.be; /* already in BE */
#endif
}

/*
** ===================================================================
**     Method      :  MMA1_GetXOffset (component MMA8451Q)
**     Description :
**         Returns the offset applied to the X value.
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
int16_t MMA1_GetXOffset(void)
{
  return CalNxOff;
}

/*
** ===================================================================
**     Method      :  MMA1_GetYOffset (component MMA8451Q)
**     Description :
**         Returns the offset applied to the Y value.
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
int16_t MMA1_GetYOffset(void)
{
  return CalNyOff;
}

/*
** ===================================================================
**     Method      :  MMA1_GetZOffset (component MMA8451Q)
**     Description :
**         Returns the offset applied to the Z value.
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
int16_t MMA1_GetZOffset(void)
{
  return CalNzOff;
}

/*
** ===================================================================
**     Method      :  MMA1_GetX1gValue (component MMA8451Q)
**     Description :
**         Returns the value for 1g for channel  X.
**     Parameters  : None
**     Returns     :
**         ---             - 1g value for X
** ===================================================================
*/
int16_t MMA1_GetX1gValue(void)
{
  return 4096;
}

/*
** ===================================================================
**     Method      :  MMA1_GetY1gValue (component MMA8451Q)
**     Description :
**         Returns the value for 1g for channel  Y.
**     Parameters  : None
**     Returns     :
**         ---             - 1g value for Y
** ===================================================================
*/
int16_t MMA1_GetY1gValue(void)
{
  return 4096;
}

/*
** ===================================================================
**     Method      :  MMA1_GetZ1gValue (component MMA8451Q)
**     Description :
**         Returns the value for 1g for channel  Z.
**     Parameters  : None
**     Returns     :
**         ---             - 1g value for Z
** ===================================================================
*/
int16_t MMA1_GetZ1gValue(void)
{
  return 4096;
}

/*
** ===================================================================
**     Method      :  MMA1_GetX (component MMA8451Q)
**     Description :
**         Retrieves the value for the X axis. The value is adjusted
**         with the zero calibration value (0 for 0 g, negative for
**         negative acceleration and positive for positive acceleration).
**     Parameters  : None
**     Returns     :
**         ---             - Measured X value
** ===================================================================
*/
int16_t MMA1_GetX(void)
{
  int16_t value;

  value = (int16_t)MMA1_MeasureGetRawX();
  value += CalNxOff; /* adjust with calibration offset */
  return value;
}

/*
** ===================================================================
**     Method      :  MMA1_GetY (component MMA8451Q)
**     Description :
**         Retrieves the value for the Y axis. The value is adjusted
**         with the zero calibration value (0 for 0 g, negative for
**         negative acceleration and positive for positive acceleration).
**     Parameters  : None
**     Returns     :
**         ---             - Measured Y value
** ===================================================================
*/
int16_t MMA1_GetY(void)
{
  int16_t value;

  value = (int16_t)MMA1_MeasureGetRawY();
  value += CalNyOff; /* adjust with calibration offset */
  return value;
}

/*
** ===================================================================
**     Method      :  MMA1_GetZ (component MMA8451Q)
**     Description :
**         Retrieves the value for the Z axis. The value is adjusted
**         with the zero calibration value (0 for 0 g, negative for
**         negative acceleration and positive for positive acceleration).
**     Parameters  : None
**     Returns     :
**         ---             - Measured Z value
** ===================================================================
*/
int16_t MMA1_GetZ(void)
{
  int16_t value;

  value = (int16_t)MMA1_MeasureGetRawZ();
  value += CalNzOff; /* adjust with calibration offset */
  return value;
}

/*
** ===================================================================
**     Method      :  MMA1_ParseCommand (component MMA8451Q)
**     Description :
**         Shell Command Line parser. This method is enabled/disabled
**         depending on if you have the Shell enabled/disabled in the
**         properties.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * cmd             - Pointer to command string
**       * handled         - Pointer to variable which tells if
**                           the command has been handled or not
**       * io              - Pointer to I/O structure
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte MMA1_ParseCommand(const unsigned char *cmd, bool *handled, const CLS1_StdIOType *io)
{
  if (UTIL1_strcmp((char*)cmd, CLS1_CMD_HELP)==0 || UTIL1_strcmp((char*)cmd, "MMA1 help")==0) {
    *handled = TRUE;
    return PrintHelp(io);
  } else if ((UTIL1_strcmp((char*)cmd, CLS1_CMD_STATUS)==0) || (UTIL1_strcmp((char*)cmd, "MMA1 status")==0)) {
    *handled = TRUE;
    return PrintStatus(io);
  } else if (UTIL1_strcmp((char*)cmd, (char*)"MMA1 enable")==0) {
    MMA1_Enable();
    *handled = TRUE;
  } else if (UTIL1_strcmp((char*)cmd, (char*)"MMA1 disable")==0) {
    MMA1_Disable();
    *handled = TRUE;
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  MMA1_SetFastMode (component MMA8451Q)
**     Description :
**         Turns the F_READ (Fast Read Mode) on or off
**     Parameters  :
**         NAME            - DESCRIPTION
**         on              - if to turn the F_READ mode on or off
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte MMA1_SetFastMode(bool on)
{
  uint8_t val, res;

  res = GI2C1_ReadByteAddress8(MMA1_I2C_ADDR, MMA1_CTRL_REG_1, &val);
  if (res!=ERR_OK) {
    return res;
  }
  if (on) {
    val |= MMA1_F_READ_BIT_MASK; /* enable F_READ: Fast read mode, data format limited to single byte (auto increment counter will skip LSB) */
  } else {
    val &= ~MMA1_F_READ_BIT_MASK; /* disable F_READ: Fast read mode, data format limited to single byte (auto increment counter will skip LSB) */
  }
  return GI2C1_WriteByteAddress8(MMA1_I2C_ADDR, MMA1_CTRL_REG_1, val);
}

/*
** ===================================================================
**     Method      :  MMA1_Enable (component MMA8451Q)
**     Description :
**         Enables the device with setting the ACTIVE bit in the CTRL
**         register 1
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte MMA1_Enable(void)
{
  uint8_t val, res;

  res = GI2C1_ReadByteAddress8(MMA1_I2C_ADDR, MMA1_CTRL_REG_1, &val);
  if (res!=ERR_OK) {
    return res;
  }
  val |= MMA1_ACTIVE_BIT_MASK; /* enable device */
  return GI2C1_WriteByteAddress8(MMA1_I2C_ADDR, MMA1_CTRL_REG_1, val);
}

/*
** ===================================================================
**     Method      :  MMA1_Disable (component MMA8451Q)
**     Description :
**         Disables the device with clearing the ACTIVE bit in the CTRL
**         register 1
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte MMA1_Disable(void)
{
  uint8_t val, res;

  res = GI2C1_ReadByteAddress8(MMA1_I2C_ADDR, MMA1_CTRL_REG_1, &val);
  if (res!=ERR_OK) {
    return res;
  }
  val &= ~MMA1_ACTIVE_BIT_MASK; /* disable device */
  return GI2C1_WriteByteAddress8(MMA1_I2C_ADDR, MMA1_CTRL_REG_1, val);
}

/*
** ===================================================================
**     Method      :  MMA1_isEnabled (component MMA8451Q)
**     Description :
**         Returns the status of the the ACTIVE bit in the CTRL
**         register 1
**     Parameters  :
**         NAME            - DESCRIPTION
**       * isEnabled       - Pointer to where to store the
**                           result, TRUE if ACTIVE bit is set, FALSE
**                           otherwise
**     Returns     :
**         ---             - error code
** ===================================================================
*/
byte MMA1_isEnabled(bool *isEnabled)
{
  uint8_t val, res;

  res = GI2C1_ReadByteAddress8(MMA1_I2C_ADDR, MMA1_CTRL_REG_1, &val);
  if (res!=ERR_OK) {
    *isEnabled = FALSE;
    return ERR_FAILED;
  }
  *isEnabled = (val&MMA1_ACTIVE_BIT_MASK)!=0; /* TRUE if bit is set, FALSE otherwise */
  return ERR_OK;
}

/* END MMA1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.10]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
